bhcc_case_management.settings:
  type: config_entity
  label: 'bhcc_case_management record config'
  mapping:
    citizen_id_service_url:
      label: 'Citizen id service url'
      type: string
    case_management_post_url:
      label: 'Case management post url'
      type: string
    case_management_auth_header:
      label: 'Case management auth header'
      type: string
bhcc_case_management.bhcc_contact_management_group.*:
  type: config_entity
  label: 'Contact management group'
  mapping:
    id:
      type: string
      label: 'ID'
    name:
      type: label
      label: 'Name'
    post_url:
      type: string
      label: 'Post URL'
    auth_header:
      type: string
      label: 'Auth header'
    uuid:
      type: string